version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: the_tutor
    steps:
      - checkout
      - run:
          name: Wait for Database Connection
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: sudo apt-get update && sudo apt-get install mysql-client
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn integration-test
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  sample:
    jobs:
      - build-and-test